# Generated by Django 5.1.15 on 2026-08-26 16:12

import apps.innovation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0003_complaint_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Registered name of the partner organisation', max_length=200)),
                ('partner_type', models.CharField(choices=[('INDUSTRY', 'Industry / Corporate'), ('STARTUP', 'Startup'), ('MSME', 'MSME'), ('CSR', 'CSR Foundation'), ('RESEARCH_LAB', 'Research Laboratory'), ('INCUBATOR', 'Incubator / Innovation Hub')], db_index=True, default='INDUSTRY', max_length=30)),
                ('sectors', models.JSONField(blank=True, default=list, help_text='Thematic domains the partner is interested in supporting')),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry Partner',
                'verbose_name_plural': 'Industry Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Registered name of the Higher Education Institution', max_length=200)),
                ('short_name', models.CharField(blank=True, default='', help_text="Common abbreviation e.g. 'BIT Sindri'", max_length=50)),
                ('district', models.CharField(db_index=True, help_text='District where the institution is located', max_length=100)),
                ('state', models.CharField(default='Jharkhand', help_text='State where the institution is located', max_length=100)),
                ('expertise_domains', models.JSONField(blank=True, default=list, help_text="Thematic domains this institution can take on, e.g. ['WATER', 'ENVIRONMENT']")),
                ('innovation_centre', models.CharField(blank=True, default='', help_text="Name of the institution's innovation / incubation centre, if any", max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Nodal officer contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the institution is currently accepting challenges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University / HEI',
                'verbose_name_plural': 'Universities / HEIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InnovationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=apps.innovation.models.generate_project_code, help_text='Unique project tracking code', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Project / research proposal title', max_length=200)),
                ('proposal_summary', models.TextField(help_text='Proposed approach to solving the challenge')),
                ('faculty_mentor_name', models.CharField(help_text='Faculty member mentoring the student team', max_length=150)),
                ('student_members', models.JSONField(blank=True, default=list, help_text="Multidisciplinary student team, e.g. ['Asha Kumari (Civil)', ...]")),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposal Submitted'), ('APPROVED', 'Proposal Approved'), ('IN_PROGRESS', 'Research / Development In Progress'), ('PROTOTYPE', 'Prototype Built'), ('TESTING', 'Field Testing & Validation'), ('DEPLOYED', 'Deployed in Community'), ('ON_HOLD', 'On Hold'), ('REJECTED', 'Rejected / Withdrawn')], db_index=True, default='PROPOSED', max_length=20)),
                ('outcome_notes', models.TextField(blank=True, default='', help_text='Validated outcome, IP generated, or deployment summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(help_text='The citizen-reported societal challenge being solved', on_delete=django.db.models.deletion.CASCADE, related_name='innovation_projects', to='complaints.complaint')),
                ('created_by', models.ForeignKey(blank=True, help_text='University coordinator who registered this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(help_text='Institution that claimed this challenge', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='innovation.university')),
            ],
            options={
                'verbose_name': 'Innovation Project',
                'verbose_name_plural': 'Innovation Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document, report or test result', null=True, upload_to='project_milestones/%Y/%m/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='innovation.innovationproject')),
            ],
            options={
                'verbose_name': 'Project Milestone',
                'verbose_name_plural': 'Project Milestones',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_type', models.CharField(choices=[('MENTORSHIP', 'Technical Mentorship'), ('FUNDING', 'Funding / CSR Grant'), ('PROTOTYPING', 'Prototyping Support'), ('LAB_ACCESS', 'Laboratory / Facility Access'), ('PILOT_DEPLOYMENT', 'Pilot Deployment Partner'), ('TECH_TRANSFER', 'Technology Transfer & Commercialisation')], db_index=True, max_length=30)),
                ('description', models.TextField(help_text='What exactly the partner is offering')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Funding amount in INR, where applicable', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted by Institution'), ('DECLINED', 'Declined')], db_index=True, default='OFFERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('offered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_offers', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_offers', to='innovation.industrypartner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_offers', to='innovation.innovationproject')),
            ],
            options={
                'verbose_name': 'Support Offer',
                'verbose_name_plural': 'Support Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeRoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('EDUCATION', 'Education & Skilling'), ('AGRICULTURE', 'Agriculture & Allied Sectors'), ('HEALTHCARE', 'Healthcare & Public Health'), ('WATER', 'Water Resources & Sanitation'), ('ENVIRONMENT', 'Environment & Climate'), ('ENERGY', 'Energy & Renewables'), ('URBAN_DEV', 'Urban Development & Infrastructure'), ('ACCESSIBILITY', 'Accessibility & Inclusion'), ('PUBLIC_ADMIN', 'Public Administration & Service Delivery'), ('RURAL_LIVELIHOOD', 'Rural Livelihoods & Employment'), ('OTHER', 'Other / Multidisciplinary')], default='OTHER', max_length=30)),
                ('reason', models.CharField(blank=True, default='', help_text='Why this institution was selected e.g. domain + district match', max_length=300)),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='complaints.complaint')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_logs', to='innovation.university')),
            ],
            options={
                'verbose_name': 'Challenge Routing Log',
                'verbose_name_plural': 'Challenge Routing Logs',
                'ordering': ['-routed_at'],
            },
        ),
    ]
