# Generated by Django 5.1.15 on 2026-08-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationproject',
            name='academic_credits',
            field=models.PositiveSmallIntegerField(default=0, help_text='Academic credits the institution awards for this project, per its NEP 2020 credit framework'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='counts_as_capstone',
            field=models.BooleanField(default=False, help_text='Whether this project satisfies a capstone / final-year project requirement'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='counts_as_internship',
            field=models.BooleanField(default=False, help_text='Whether this project satisfies an internship requirement'),
        ),
        migrations.CreateModel(
            name='StudentContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text="Name of the student being credited, e.g. 'Asha Kumari (Civil)'", max_length=150)),
                ('role', models.CharField(blank=True, default='', help_text="Role played on the team, e.g. 'Lead Researcher', 'Field Data Collection'", max_length=100)),
                ('contribution_summary', models.TextField(blank=True, default='', help_text='What this student specifically did or delivered')),
                ('credits_earned', models.PositiveSmallIntegerField(default=0, help_text='Academic credits earned by this student for their contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_contributions', to='innovation.innovationproject')),
            ],
            options={
                'verbose_name': 'Student Contribution',
                'verbose_name_plural': 'Student Contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
