# Generated by Django 5.1.15 on 2026-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0002_innovationproject_academic_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationproject',
            name='patent_details',
            field=models.CharField(blank=True, default='', help_text='Patent application number / title, if filed', max_length=300),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='patent_filed',
            field=models.BooleanField(default=False, help_text='Whether a patent or other IP was filed as a result of this project'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='people_benefited',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated number of citizens who benefit from the deployed solution', null=True),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='solution_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of building and deploying the solution, in INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='startup_created',
            field=models.BooleanField(default=False, help_text='Whether a startup was incorporated as a result of this project'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='startup_name',
            field=models.CharField(blank=True, default='', help_text='Name of the startup, if one was created', max_length=200),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='villages_covered',
            field=models.PositiveIntegerField(blank=True, help_text='Number of villages / wards / localities the deployed solution covers', null=True),
        ),
    ]
