services:
  - type: web
    name: civicsense-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt -r requirements-prod.txt
    startCommand: bash start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DB_ENGINE
        value: sqlite
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11.9"
