# Generated by Django 5.1.15 on 2026-08-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry_partner',
            field=models.ForeignKey(blank=True, help_text='Partner organisation this user represents (INDUSTRY role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='innovation.industrypartner'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, help_text='Institution this coordinator represents (UNIVERSITY role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinators', to='innovation.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('OFFICER', 'Department Officer'), ('ADMIN', 'Municipal Administrator'), ('UNIVERSITY', 'University / HEI Coordinator'), ('INDUSTRY', 'Industry / Startup Partner')], db_index=True, default='CITIZEN', help_text='Role determining platform permissions', max_length=20),
        ),
    ]
