# Generated by Django 6.0.2 on 2026-08-09 12:41

import apps.complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, default=apps.complaints.models.generate_ticket_id, help_text='Unique tracking code for citizens and officers', max_length=30, unique=True)),
                ('title', models.CharField(help_text='Brief summary of the civic problem', max_length=200)),
                ('description', models.TextField(help_text='Detailed problem description with context')),
                ('category', models.CharField(choices=[('ROADS_POTHOLES', 'Road Damage / Potholes / Footpaths'), ('WASTE_GARBAGE', 'Garbage Dump / Overflowing Bins / Cleanliness'), ('STREETLIGHT_POWER', 'Streetlight Not Working / Sparking Cables'), ('WATER_LEAKAGE', 'Water Pipeline Leakage / Contamination / Low Pressure'), ('DRAINAGE_OVERFLOW', 'Blocked Drains / Sewage Overflow / Flooding'), ('PUBLIC_SAFETY_HAZARD', 'Open Manhole / Unsafe Building / Stray Animals'), ('POLLUTION_AIR_NOISE', 'Air / Noise / Industrial Pollution / Illegal Burning'), ('OTHER', 'Other Civic Grievance')], db_index=True, default='OTHER', help_text='Municipal grievance category', max_length=50)),
                ('auto_classified', models.BooleanField(default=True, help_text='Whether category was predicted by AI NLP classifier')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence score for classification (0.0 to 1.0)')),
                ('urgency', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Urgency'), ('CRITICAL', 'Critical / Emergency Hazard')], db_index=True, default='MEDIUM', help_text='Urgency level determined by priority engine', max_length=20)),
                ('priority_score', models.PositiveIntegerField(db_index=True, default=50, help_text='Dynamic priority score (1-100) calculated by AI')),
                ('status', models.CharField(choices=[('PENDING', 'Submitted / Pending Review'), ('VERIFIED', 'Verified by AI & Officer'), ('IN_PROGRESS', 'In Progress / Assigned to Field Team'), ('RESOLVED', 'Resolved & Closed'), ('REJECTED', 'Rejected / Duplicate / Invalid')], db_index=True, default='PENDING', help_text='Current lifecycle state of the grievance', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude', max_digits=10, null=True)),
                ('address', models.CharField(blank=True, default='', help_text='Street address / locality name', max_length=300)),
                ('landmark', models.CharField(blank=True, default='', help_text='Nearby prominent landmark', max_length=200)),
                ('ward_number', models.CharField(blank=True, db_index=True, default='Ward 1', help_text='Municipal ward number', max_length=50)),
                ('pincode', models.CharField(blank=True, default='', help_text='Postal Area Pincode', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Proof photo uploaded by citizen', null=True, upload_to='complaints/%Y/%m/')),
                ('resolution_image', models.ImageField(blank=True, help_text='Proof photo uploaded by officer after resolution', null=True, upload_to='resolutions/%Y/%m/')),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Official resolution summary and field action report')),
                ('assigned_department', models.CharField(choices=[('ROADS', 'Roads & Infrastructure (PWD)'), ('SANITATION', 'Solid Waste & Sanitation'), ('ELECTRICITY', 'Electricity & Streetlighting'), ('WATER_SUPPLY', 'Water Supply Board'), ('DRAINAGE', 'Drainage & Sewage'), ('PUBLIC_SAFETY', 'Public Safety & Law Enforcement'), ('HEALTHCARE', 'Public Health & Pollution Control'), ('GENERAL', 'General Municipal Administration')], db_index=True, default='GENERAL', help_text='Municipal department handling this issue', max_length=50)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flagged if duplicate of an existing complaint')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='AI-extracted keywords and phrases')),
                ('upvotes_count', models.PositiveIntegerField(default=0, help_text='Number of community citizens who upvoted / confirmed this issue')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Civic Complaint',
                'verbose_name_plural': 'Civic Complaints',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="e.g. 'SUBMITTED', 'VERIFIED', 'STATUS_CHANGED', 'ASSIGNED', 'RESOLVED'", max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
