# Generated by Django 6.0.2 on 2026-08-09 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, help_text='Field Officer assigned to resolve this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen',
            field=models.ForeignKey(help_text='Citizen who lodged the grievance', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Parent original complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_reports', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintactivitylog',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintactivitylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintupvote',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintupvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='complaintupvote',
            unique_together={('complaint', 'user')},
        ),
    ]
