# Generated by Django 5.1.15 on 2026-08-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='domain',
            field=models.CharField(choices=[('EDUCATION', 'Education & Skilling'), ('AGRICULTURE', 'Agriculture & Allied Sectors'), ('HEALTHCARE', 'Healthcare & Public Health'), ('WATER', 'Water Resources & Sanitation'), ('ENVIRONMENT', 'Environment & Climate'), ('ENERGY', 'Energy & Renewables'), ('URBAN_DEV', 'Urban Development & Infrastructure'), ('ACCESSIBILITY', 'Accessibility & Inclusion'), ('PUBLIC_ADMIN', 'Public Administration & Service Delivery'), ('RURAL_LIVELIHOOD', 'Rural Livelihoods & Employment'), ('OTHER', 'Other / Multidisciplinary')], db_index=True, default='OTHER', help_text='Academic thematic domain, derived from the AI category', max_length=30),
        ),
    ]
