# Generated by Django 5.1.15 on 2026-08-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_domain'),
        ('innovation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='routed_university',
            field=models.ForeignKey(blank=True, help_text='HEI this challenge was routed to for innovation-driven resolution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_challenges', to='innovation.university'),
        ),
    ]
